version: "3"

services:
  server:
    # image: ${GITEE_DOCKER_IMAGE}
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: "Asia/Shanghai"
      TIMEOUT: 10000
