version: "3"

services:
  server:
    container_name: 'wechat-official-helper'
    image: ${DOCKER_IMAGE:-caomeiyouren/wechat-official-helper}
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: "Asia/Shanghai"
      TIMEOUT: 10000
